# 2. NumPy 배열

* NumPy에는 ndarray라는 데이터 타입의 배열이 생성된다.
* ndarray는 같은 타입의 데이터만 저장할 수 있다.
* Python의 list보다 계산 속도가 빠르다

In [1]:
# import 하기
import numpy as np

## 2-1. np.array() 함수로 생성하기
### 1차원 배열 생성하기

In [14]:
# 1차원 배열
arr = np.array([1, 2, 3, 4]) #튜플로 전달할 수도 있음. 하지만 리스트가 일반적이다.
arr #마지막 줄은 print가 default라 쓰지 않아도 상관 없다.

array([1, 2, 3, 4])

In [15]:
# type 확인
type(arr)

numpy.ndarray

In [16]:
np.array(1, 2, 3, 4) 
#에러가 난다. 왜냐하면 array의 인자는 1개만 있어야 한다. (data가 1개 들어가야 한다!)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [17]:
# ndarray에 들어있는 data의 타입을 알고 싶을 때
arr.dtype

dtype('int32')

In [18]:
# overflow 테스트
arr = np.array([2147483647, 2, 3, 4]) #2147483647이 최댓값임
arr

array([2147483647,          2,          3,          4])

In [19]:
arr = np.array([2147483648, 2, 3, 4], dtype = np.int32)
arr
#따라서 데이터 타입을 int64로 바꾸어 주면 된다. dtype=~ 는 optional argument이다.

OverflowError: Python int too large to convert to C long

In [20]:
arr = np.array([1, 2, 3, 4], dtype=float)
arr

array([1., 2., 3., 4.])

In [21]:
arr.dtype

dtype('float64')

In [22]:
# shape : 각 차원의 배열의 size (모양)
arr.shape

(4,)

In [23]:
# size : 배열의 전체 element 수
arr.size

4

In [24]:
# ndim : 차원의 수
arr.ndim

1

In [25]:
arr = np.array([1, 2, 3, 3.14])
arr

array([1.  , 2.  , 3.  , 3.14])

In [26]:
arr = np.array([1, 2, 3, 3.14], dtype=int) #np.int32랑 int 랑 같은 말이다.
arr

array([1, 2, 3, 3])

In [27]:
arr = np.array([1, 3.14, '1234'])
arr

array(['1', '3.14', '1234'], dtype='<U32')

* dtype에 <U32 가 찍혔는데 이게 하나하나 다 의미가 있다.  
big-endian, little-endian 이라는 게 있다.  
우리가 메모리를 어떻게 저장하느냐에 따라서 이 두 가지 형태가 존재하는데, 일의 자리로 갈수록 작은 단위, 높은 자리로 갈수록 큰 단위라고 하면, 큰 단위부터 메모리에 할당하는 방식이 빅엔드, 그 반대가 리틀 엔디안이다. 대부분의 컴퓨터가 리틀 엔디안을 사용한다.  
그리고 >가 빅엔디안, <가 리틀엔디안이다.
* U는 유니코드를 뜻한다. 문자열의 길이가 32까지 default다. U32는 그런 의미다.  
만약 더 길어지면 33, 34 이런 식으로 데이터에 맞추어서 변한다.
* 마찬가지로 dtype=int로 변환 가능하다.

In [28]:
# 이미 있는 배열을 타입만 다르게 하여 새로 생성하기
new_arr = arr.astype(float) #new_arr이 복사본, arr이 원본이다. #float이나 np.float64나 똑같다.
new_arr

array([1.000e+00, 3.140e+00, 1.234e+03])

In [29]:
arr.dtype, new_arr.dtype

(dtype('<U32'), dtype('float64'))

### 2차원 배열 생성하기

In [30]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
arr2.dtype, arr2.shape, arr2.size, arr2.ndim

(dtype('int32'), (3, 4), 12, 2)

## 2-2. np.arange() 함수로 생성하기

In [34]:
# 파이썬의 range
for i in range(0, 10, 2): #0~9
    print(i)

0
2
4
6
8


### 1차원 배열 생성하기

In [35]:
# 1~10
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

### 2차원 배열 생성하기

In [36]:
# 0~11
arr = np.arange(0, 12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
arr.reshape((3, 4)) #행렬의 개수가 맞아야 한다.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
# 원본 배열의 shape를 변경하고자 할 경우 (잘 쓰지 않는다. 원본을 바꾸어버리는 것은 위험하기 때문이다.)
arr.shape = (3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2-3. np.zeros() 함수

In [39]:
# 1차원 배열
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [42]:
# 2차원 배열
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2-4. np.ones() 함수

In [43]:
# 1차원 배열
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [44]:
# 2차원 배열
arr2 = np.ones((3,4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 2-5. np.linspace() 함수

In [61]:
arr = np.linspace(0, 10, 5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [62]:
arr = np.linspace(0, 10)
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [63]:
arr.shape

(50,)

In [64]:
arr2 = arr.reshape((10, 5))
arr2

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653],
       [ 1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286],
       [ 3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918],
       [ 5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551],
       [ 7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184],
       [ 9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

## 2-6. np.full() 함수

In [65]:
# 특정 값으로 배열을 생성할 경우
arr = np.full(4, 10)
arr

array([10, 10, 10, 10])

In [66]:
arr2 = np.full((3,4), 10)
arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

## 2-7. np.eye() 함수

In [67]:
# 단위 행렬 (항등 행렬) 
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 2-8. np.random() 함수

In [3]:
arr = np.random.rand(4)
arr

array([0.22111842, 0.39210428, 0.68315212, 0.2924848 ])

In [4]:
arr2 = np.random.rand(3, 4)
arr2

array([[0.6360334 , 0.86932106, 0.34826022, 0.18086207],
       [0.35983263, 0.40258778, 0.06671948, 0.21292948],
       [0.35882386, 0.47659343, 0.73703978, 0.4234619 ]])

In [10]:
arr = np.random.randint(5, size=10)
arr

array([4, 0, 0, 1, 3, 4, 4, 4, 1, 3])

In [11]:
arr2 = np.random.randint(1, 5, size=(3,4))
arr2

array([[3, 2, 1, 1],
       [4, 3, 2, 1],
       [4, 3, 3, 3]])

In [12]:
#일정한 랜덤값을 만드려면?
np.random.seed(123)
np.random.rand(3, 4)

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477],
       [0.71946897, 0.42310646, 0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752, 0.34317802, 0.72904971]])

## 2-9. Numpy 배열 Save & Load

In [4]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [6]:
np.save('my_arr', arr) #이렇게 하면 10_NumPy 파일 안에 생성된다.

In [14]:
new_arr = np.load('my_arr.npy') #laod할 때 확장명을 붙여야 한다는 것에 주의!
new_arr

array([0, 1, 2, 3, 4])