# 3. 연산

## 3-1. 산술연산

### 1차원 배열

In [1]:
import numpy as np

In [10]:
a = np.arange(1, 5) # 1~4
b = np.arange(5, 9) # 5~8
a, b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [4]:
a.shape, b.shape

((4,), (4,))

In [5]:
a + b

array([ 6,  8, 10, 12])

In [6]:
a - b

array([-4, -4, -4, -4])

In [7]:
a * b

array([ 5, 12, 21, 32])

In [8]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

### 2차원 배열

In [4]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b = np.arange(7, 13).reshape(2, 3)
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [18]:
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [20]:
a - b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [21]:
# 단순 곱셈 (하지만 행렬곱은 이렇게는 안 쓴다. 이렇게 쓰면 안 된다.)
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [24]:
a / b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

### 행렬의 곱셈 (dot product)

행렬의 곱셈 (dot product)를 할 때는 앞에 있는 행렬의 열과 뒤에 있는 행렬의 행의 개수가 각각 같아야 한다.

In [7]:
### 중요    
b = np.arange(1, 7).reshape(3, 2) #행렬곱의 조건 맞추기 (앞 행렬의 열과 뒤 행령의 행의 개수가 같아야 한다.)
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [8]:
np.dot(a, b)

array([[22, 28],
       [49, 64]])

In [9]:
a.dot(b) #이렇게도 쓸 수 있지만 numpy에서 제공하는 함수인지 알기 어려우므로 np.dot 함수를 더 많이 사용한다.

array([[22, 28],
       [49, 64]])

In [10]:
# 비교
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a < 4

array([[ True,  True,  True],
       [False, False, False]])

### 배열과 숫자(Scalar)와의 연산 : Broadcasting

In [13]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [14]:
a + 3

array([4, 5, 6])

In [15]:
a - 3

array([-2, -1,  0])

In [16]:
a * 3

array([3, 6, 9])

In [17]:
a / 3

array([0.33333333, 0.66666667, 1.        ])

## 3-2. Aggregation 함수

### 1차원 배열

In [18]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [19]:
# max값 찾기
np.max(a)

5

In [20]:
a.max() #이것도 np를 앞에 붙이는 것을 권장한다.

5

In [21]:
# min값 찾기
np.min(a)

1

In [23]:
a.min()

1

In [25]:
# 배열요소의 합 구하기
np.sum(a)

15

In [27]:
# 평균구하기
np.mean(a)

3.0

In [28]:
a.mean()

3.0

In [29]:
# 이상차(Outlier)가 있는 경우에는 mean값이 배열을 대표할 수 업음
a = np.array([1, 2, 3, 4, 100])
np.mean(a)

22.0

위와 같은 경우에는 mean값인 22가 위 데이터를 잘 대표한다고 볼 수 없다.  
이 때 100과 같은 데이터를 **이상치**라고 부른다. 이상치는 영어로 **Outlier**라고 부른다.  
이런 경우 **중앙값(중위값)**을 사용할 수 있는데, ``median``함수를 사용한다.  
참고로 데이터 개수가 짝수인 경우에는 가운데 두 값의 평균을 중앙값으로 사용한다.

In [30]:
# 중앙값(중위값)
np.median(a)

3.0

In [31]:
# 짝수인 경우
a = np.array([1, 100, 2, 4])
np.median(a)

3.0

In [32]:
# std : 표준편차(standard deviation)
np.std(a)

42.30469832063574

### 2차원 배열

In [33]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.max(a)

6

In [35]:
np.min(a)

1

그냥 max, min 하면 전체 6개 중에서 골라진다. 근데 2차원부터는 **축(axis)**의 개념이 도입된다. 좌표평면처럼 말이다.

In [36]:
np.max(a, axis=0) #axis=0란 행(row)이라고 생각하면 된다. -> 모든 행에 대하여 max값을 구하는 것이다.

array([4, 5, 6])

In [37]:
np.max(a, axis=1) #axis=1은 열(column)이다. -> 모든 열에 대하여 max값을 구하는 것이다.

array([3, 6])

In [38]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.sum(a)

21

In [40]:
np.sum(a, axis=0)

array([5, 7, 9])

In [41]:
np.sum(a, axis=1)

array([ 6, 15])

In [42]:
# cumsum
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

cumsum은 cumulative의 약자이다. 즉 누적해가면서 더한다.

In [43]:
np.cumsum(a, axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [44]:
np.cumsum(a, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [3]:
# corrcoef(상관계수) : 두 변수 사이에 어느정도의 상관관계가 있는지를 나타내는 수치

# 키와 몸무게의 상관관계
# 

h = [160, 165, 170, 180]
w = [47, 55, 70, 85]
np.corrcoef(h, w)

array([[1.        , 0.99040485],
       [0.99040485, 1.        ]])

아래는 np.corrcoef 말고 피어슨 상관 계수의 정의에 따라 correlation coefficient를 구하는 과정이다.

In [4]:
ha = np.mean(h)
wa = np.mean(w)
ha, wa

(168.75, 64.25)

In [6]:
a = np.sqrt(np.sum((h - ha) ** 2)) #sqrt는 루트(2제곱근)를 말한다.
a

14.79019945774904

In [7]:
b = np.sqrt(np.sum((w - wa) ** 2))
b

29.098969053902923

In [8]:
c = np.sum((h - ha) * (w - wa))
c

426.25

In [9]:
r = c / (a * b)
r

0.990404850180661