# 5. 인덱싱과 슬라이싱

## 5-1. 인덱싱

In [2]:
import numpy as np

In [2]:
# 1차원 배열
arr = np.arange(1, 11) # 1~10까지
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[1], arr[4], arr[-1] #arr[-1] = arr[9]

(2, 5, 10)

In [6]:
# 2차원 배열
arr2 = np.arange(1, 13).reshape(3, 4) #1~12까지 3*4 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
arr2[0][1], arr2[1][2], arr2[-1][-1]

(2, 7, 12)

In [9]:
# 다차원 indexing
arr2[0, 1], arr2[1, 2], arr2[-1, -1]

(2, 7, 12)

## 5-2. 슬라이싱

In [10]:
# 1차원 배열
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# 슬라이싱 [start:end:step] ☞ 마찬가지로 end의 실질적 범위는 -1을 해야 한다.
arr[2:6]

array([3, 4, 5, 6])

In [13]:
# 3~끝까지
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# 처음~6까지
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [16]:
# 처음~끝까지
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# 슬라이싱한 후 값을 변경하면 원본 배열에 영향을 미칠까?
new_arr = arr[2:6]
new_arr

array([3, 4, 5, 6])

In [18]:
new_arr[0] = 100
new_arr

array([100,   4,   5,   6])

In [19]:
arr

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [20]:
# 원본배열도 수정되기 때문에 np.copy함수를 이용하자.
copy_arr = np.copy(arr)
copy_arr

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [21]:
arr[::2]

array([  1, 100,   5,   7,   9])

In [22]:
# 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# 첫번째 행을 가져오기
arr2[0, :]

array([1, 2, 3, 4])

In [32]:
# 세번째 열을 가져오기
arr2[:, 2]

array([ 3,  7, 11])

In [33]:
# 첫번째, 두번째 행을 가져오기
arr2[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
# 두번째, 세번째 열을 가져오기
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [38]:
# 2,3,6,7 가져오기
arr2[:2, 1:3] #arr2[:2, 1:-1]로도 쓸 수 있다는 걸 알아야 한다. (왜냐하면 마지막 -1이기 때문)

array([[2, 3],
       [6, 7]])

## 5-3 Fancy Indexing
fancy는 '좋아하다'라는 뜻이 있다. fancy 인덱싱은 좋아하는 것만 빼내는 방법이다.

In [5]:
# one-dimensional array
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
# to make [3,6,8] 1-dim array
np.array([arr[2], arr[5], arr[7]])

array([3, 6, 8])

Above is incomfortable. So we can use fancy indexing and facilitate it.

In [7]:
# fancy indexing - to make array with index
arr[[2, 5, 7]]

array([3, 6, 8])

In [8]:
# two-dimensional array
arr2 = np.arange(1, 13).reshape(3, 4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
arr2[[0, 2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [11]:
arr2[[1]] # you have to use double bracket even if you want to extract only one element.

array([[5, 6, 7, 8]])

How to extract ``2, 3, 6, 7, 10, 11``

In [14]:
# slicing
arr2[:, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [13]:
# fancy indexing
arr2[:, [1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## 5-4. Boolean Indexing
Actually, Boolean indexing is most common method of extracting particullar elements.

In [18]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [19]:
cond = [True, True, False, False, True]

In [20]:
# Boolean indexing
arr[cond]

array([0, 1, 4])

Why we use boolean indexing mostly? The reason is handiness.  
Look at the following.

In [32]:
arr > 2

array([False, False, False,  True,  True])

In [26]:
arr[arr > 2]

array([3, 4])

In [25]:
# select even number
arr[arr % 2 == 0]

array([0, 2, 4])

In [29]:
# less than 1 or more than 3 (that is 0 and 4)
arr[(arr < 1) | (arr > 3)] # 1. care about parenthesis. 2. use | but not ||

array([0, 4])

In [30]:
# more than 2 and less than 3 (that is 2 and 3)
arr[(arr >= 2) & (arr <= 3)]

array([2, 3])